sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - 16.16.0
script:
  - npm run ci
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
cache:
  yarn: false
notifications:
  email: false
after_success:
  - npm run codecov
